import { ContactForm } from '@/components/contact/ContactForm';
import { FaqSection } from '@/components/contact/FaqSection';
import { getFaqs } from '@/lib/api';

export const metadata = { title: 'Contact and support', description: 'Contact Grabin support about orders, products, sizing, and custom requests.' };

export default function Page() {
  return <div className="mx-auto max-w-7xl px-6 pb-20 pt-16 lg:px-10"><section className="grid gap-12 border-b border-line pb-16 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="text-sm font-black uppercase tracking-[0.2em] text-moss">Contact / Support</p><h1 className="mt-5 text-7xl font-black leading-[0.82] tracking-[-0.09em]">Let&apos;s talk.</h1></div><div className="max-w-xl"><p className="text-xl leading-8 text-ink/65">Questions about an order, a product, or finding the right fit? Send us a note and our small team will point you in the right direction.</p><div className="mt-8 flex flex-wrap gap-x-8 gap-y-3 text-sm font-bold"><a href="mailto:hello@grabin.example" className="text-moss hover:text-ink">hello@grabin.example</a><span>Mon-Fri / 9:00-17:00</span></div></div></section><div className="mt-12 grid gap-12 lg:grid-cols-[1fr_0.8fr]"><section className="rounded-[2rem] border border-line bg-white/35 p-6 sm:p-10"><h2 className="mb-7 text-2xl font-black tracking-[-0.05em]">Send a message</h2><ContactForm /></section><aside className="rounded-[2rem] bg-lime p-8"><p className="text-sm font-black uppercase tracking-[0.14em]">Before you write</p><h2 className="mt-16 text-4xl font-black leading-[0.9] tracking-[-0.07em]">The answer might already be here.</h2><p className="mt-5 text-sm leading-6 text-ink/65">Check the FAQ for quick answers about shipping, returns, sizing, and care.</p><a href="#faq" className="mt-7 inline-block text-sm font-black uppercase tracking-[0.12em]">Jump to FAQ -&gt;</a></aside></div><FaqSection faqs={getFaqs()} /></div>;
}
