import Link from 'next/link';

export default function Page() {
  return (
    <div className="mx-auto max-w-7xl px-6 pb-20 pt-16 lg:px-10">
      <section className="grid gap-12 border-b border-line pb-20 lg:grid-cols-[1.1fr_0.9fr] lg:items-end">
        <div><p className="text-sm font-black uppercase tracking-[0.2em] text-moss">About Grabin / 001</p><h1 className="mt-5 max-w-3xl text-7xl font-black leading-[0.82] tracking-[-0.09em] sm:text-8xl">Built for the long way.</h1></div>
        <p className="max-w-md text-xl leading-8 text-ink/65">We make considered equipment for people who keep showing up. No noise, no shortcuts, just useful things made to move with you.</p>
      </section>
      <section className="grid gap-10 py-20 lg:grid-cols-[0.8fr_1.2fr]"><p className="text-sm font-black uppercase tracking-[0.2em] text-moss">Our point of view</p><div><p className="text-4xl font-black leading-[0.95] tracking-[-0.07em]">The best gear disappears into the effort. It fits right, works hard, and leaves room for the part that matters: the miles, the people, and the reason you started.</p><p className="mt-8 max-w-2xl text-lg leading-8 text-ink/65">Grabin started with a simple question: what would we choose if we made fewer, better things? The answer is a growing collection of footwear, apparel, and accessories shaped around daily movement, from first light to the long way home.</p></div></section>
      <section className="grid gap-4 md:grid-cols-3"><article className="rounded-[2rem] bg-lime p-7"><p className="text-sm font-black uppercase tracking-[0.14em]">01 / Useful</p><h2 className="mt-16 text-3xl font-black tracking-[-0.06em]">Function earns its place.</h2><p className="mt-4 text-sm leading-6 text-ink/65">Every detail has a job. If it does not help you move, it does not need to be there.</p></article><article className="rounded-[2rem] bg-moss p-7 text-paper"><p className="text-sm font-black uppercase tracking-[0.14em] text-paper/60">02 / Considered</p><h2 className="mt-16 text-3xl font-black tracking-[-0.06em]">Less, but better.</h2><p className="mt-4 text-sm leading-6 text-paper/65">We choose durable materials and timeless shapes over seasonal noise.</p></article><article className="rounded-[2rem] border border-line p-7"><p className="text-sm font-black uppercase tracking-[0.14em] text-moss">03 / Human</p><h2 className="mt-16 text-3xl font-black tracking-[-0.06em]">Made for real life.</h2><p className="mt-4 text-sm leading-6 text-ink/65">Performance is not a finish line. It is the confidence to take the next step.</p></article></section>
      <section className="mt-20 flex flex-col items-start justify-between gap-6 rounded-[2rem] bg-ink p-8 text-paper md:flex-row md:items-center md:p-12"><div><p className="text-sm font-black uppercase tracking-[0.2em] text-lime">Ready when you are</p><h2 className="mt-4 text-4xl font-black tracking-[-0.07em]">Find your next piece.</h2></div><Link href="/explore" className="rounded-full bg-lime px-6 py-4 text-sm font-black uppercase tracking-[0.14em] text-ink">Explore the collection</Link></section>
    </div>
  );
}
